name = "Ray Tracing"
packages = ["plyfile>=1.1.3", "geomie3d==0.0.10", "numpy-stl==3.2.0"]

[files]
"./lib/libthree.py" = ""
"./lib/utils.py" = ""

[js_modules.main]
"https://cdn.jsdelivr.net/npm/three@0.181.2/build/three.module.js" = "three"
"https://cdn.jsdelivr.net/npm/three@0.181.2/examples/jsm/controls/OrbitControls.js" = "oc"